name: Alex Does Stuff (and Things)
favicon: null
layout_spectrum: 0.66485
typography_spectrum: 0.7971
title: Alex Does Stuff (and Things)
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#02489e'
    - '#ffffff'
    - '#676a71'
    - '#3d2616'
    - '#bbb5b0'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
