name: Alex Does Stuff (and Things)
favicon: null
layout_spectrum: 1
typography_spectrum: 0.16069
title: Alex Does Stuff (and Things)
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#02489e'
    - '#ffffff'
    - '#676a71'
    - '#3d2616'
    - '#bbb5b0'
  brandStrength: 1
  lightness: 0.25
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
