typography_spectrum: 0.67025
color:
  brandColors:
    - '#02489e'
    - '#ffffff'
    - '#676a71'
    - '#3d2616'
    - '#bbb5b0'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.73679
analytics:
  google: null
  facebook: null
  twitter: null
name: Alex Does Stuff (and Things)
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Alex Does Stuff (and Things)
purpose: []
